# Generated by Django 5.1.1 on 2025-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSMEOrderingWebApp', '0002_products_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gcash', 'GCash'), ('paymaya', 'PayMaya')], max_length=10)),
                ('qr_image', models.ImageField(upload_to='qr_codes/')),
                ('recipient_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
