# Generated by Django 5.1.1 on 2025-06-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSMEOrderingWebApp', '0003_onlinepaymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_login', models.BooleanField(default=True)),
            ],
        ),
    ]
